### ISSUE TITLE
Czech Coder Layout On Waylands

### ISSUE THREAD

**Issue by MikiVanousek** [michalkahle/czech-coder-xkb#11]
The current installation instruction only work when running Ubuntu with X server. For someone who knows Linux well, this might be obvious, but I think it should be emphasized in the installation instructions.

**Comment by michalkahle** [comment]
Not obvious to me. In fact, as wayland uses xkb for keyboard layouts I hoped installation instructions were general enough to work fine there. Unfortunately, I can confirm it does not work in Fedora with wayland (except for apps using x-wayland). I'd be grateful for instructions how to make this work under wayland on behalf of other users because I do not currently use it.

**Comment by MikiVanousek** [comment]
Unfortunately, I have little experience with Linux, so I just fixed the issue by reverting back to xServer. If I ever find a solution I will let you know... :)

**Comment by MikiVanousek** [comment]
When using sway, adding 
`input * {
	xkb_layout "cz"
	xkb_variant "coder"
}
`
to your sway config (`.config/sway/config`) works.
